#·vim:·set·relativenumber·nonu·shiftwidth=2·tabstop=2·softtabstop=-1·expandtab:
version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

volumes:
  prometheus_conf:
    driver_opts:
      o: bind
      type: none
      device: /data/prometheus/config
volumes:
  prometheus_data:
    driver_opts:
      o: bind
      type: none
      device: /data/prometheus/data
networks:
  prometheus:
    driver: overlay
